- hosts: all　　# 注意这里使用的是 localhost
  gather_facts: True
  connection: local　　

  tasks:
  - name: Gather Facts of all vms in vCenter Server
    local_action:
      module: vmware_vm_facts
      hostname: '10.110.164.133'
      username: 'kuan'
      password: 'kuan'
      validate_certs: no
    register: vmfacts

  - name: Verbose virtual machine
    debug:
      msg: "{{ vmfacts.virtual_machines }}"
